site_name: My Obsidian Notes
site_url: https://namtx.dev/obsidian-publish
site_dir: public
docs_dir: ./wiki
theme:
  name: material 
  palette:
    primary: deep purple
    scheme: slate
  features:
    - navigation.tabs
plugins:
  - roamlinks
  - mkdocs-obsidian-tag-plugin
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.magiclink

