name: gh-pages-publish
on:
  push:
    branches:
      - main
      - feat/mkdocs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install -i https://test.pypi.org/simple/ mkdocs-obsidian-tag-plugin==0.0.1
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
